/* tslint:disable */
/* eslint-disable */
/**
 * Pirate Beers
 * A ecommerce app that sells beers
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Range,
    RangeFromJSON,
    RangeFromJSONTyped,
    RangeToJSON,
} from './Range';

/**
 * A model of category data data
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    image: string;
    /**
     * 
     * @type {Range}
     * @memberof Category
     */
    abv: Range;
    /**
     * 
     * @type {Range}
     * @memberof Category
     */
    ibu: Range;
    /**
     * 
     * @type {Range}
     * @memberof Category
     */
    srm: Range;
    /**
     * 
     * @type {Range}
     * @memberof Category
     */
    servingTemperature: Range;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    averagePrice: number;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    totalBeers: number;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'url': json['url'],
        'image': json['image'],
        'abv': RangeFromJSON(json['abv']),
        'ibu': RangeFromJSON(json['ibu']),
        'srm': RangeFromJSON(json['srm']),
        'servingTemperature': RangeFromJSON(json['servingTemperature']),
        'averagePrice': json['averagePrice'],
        'totalBeers': json['totalBeers'],
    };
}

export function CategoryToJSON(value?: Category | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'url': value.url,
        'image': value.image,
        'abv': RangeToJSON(value.abv),
        'ibu': RangeToJSON(value.ibu),
        'srm': RangeToJSON(value.srm),
        'servingTemperature': RangeToJSON(value.servingTemperature),
        'averagePrice': value.averagePrice,
        'totalBeers': value.totalBeers,
    };
}

